# Generated by Django 5.1.4 on 2025-01-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
                ('price', models.FloatField()),
                ('image', models.ImageField(default='', upload_to='main_app/static/uploads')),
            ],
        ),
    ]
