# Generated by Django 5.1.4 on 2025-01-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ring',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
