# Generated by Django 5.1.4 on 2025-01-12 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_ring_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('polish', models.CharField(choices=[('S', 'Soft Cloth'), ('U', 'Ultrasonic Cleaner'), ('R', 'Rotary Tool')], default='S', max_length=1)),
                ('ring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ring')),
            ],
        ),
    ]
