# Generated by Django 5.1.4 on 2025-01-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='ring',
            name='bands',
            field=models.ManyToManyField(to='main_app.band'),
        ),
    ]
